### ISSUE TITLE
Mail

### ISSUE THREAD

**Issue by danielmoessner** [lawandorga/lawandorga-backend-service#348]
# Problem

`The best problem definition consists of a single specific story that shows why the status quo doesn’t work.`

- Datenschutzbruch soll umgangen werden dass alles direkt in Law&Orga ist.
- Zeitersparnis dahingehend, dass Daten nicht copy-pasted werden müssen.

# Appetite

`How much time should be spent on this project?`

6 Wochen

# Solution

`How will the problem be solved? Add embedded and fat marker sketches.`

- Von meiner Mail aus Mails an Law and Orga schicken können immer an die selbe Adresse pro RLC. Über cc an die jeweilige Akte schicken können. Dort ist dann ein Reiter Mails und man kann jede einzelne öffnen und anzeigen lassen. 
- aktenzeichen@beispiel-rlc.law-orga.de

## Optional Features

- Zentrales Postfach anstatt einem individuellen pro RLC
- Direktes Anzeigen der Mail Adressen von den aktuellen Akten

# Rabbit holes

`What could go wrong? Or what problems might come up?`

- Wie werden die Mails abgeholt, bzw. wo entstehen diese Mail Postfächer. (Eigener Mail-Server vs Externer Mail-Server wie zB Outlook vs andere Lösungen)?
- Wie landen die Mails verschlüsselt in unserer Datenbank?

# No-gos

`What will not be done?`

-

# Next Steps

- Einführung ins System + Dummy Zugang | (Daniel, Toni, Leandra, Johannes, Tara, Daniel) ✅
- Technische Einführung (Frontend + Backend) | (Johannes, Leandra, Daniel) bis :45 (13.2)
- Design User Story Flow (Daniel, Toni, Leandra, Johannes) ab :45 (13.2)
- Design User Story Flow Zusammenfassung (Daniel, Toni, Leandra, Johannes, Tara, Quint, Daniel)
- Technische Steps und Schwierigkeiten Call (Daniel, Leandra, Johannes)

# Other Stuff

- Kommunikation Signal
- Optional Bi-Weekly Call

**Comment by LeandraH** [comment]
Email polling example from another repo from Digitalfabrik: https://github.com/digitalfabrik/opendrift-leeway-webgui/blob/main/opendrift_leeway_webgui/leeway/celery.py#L38-L52

**Comment by hauf-toni** [comment]
the corresponding figma-file is linked [📁 here](https://www.figma.com/file/vwzbdSi917VEEbdpPC3LGv/Law-%26-Orga-x-Digitalfabrik?type=design&node-id=2%3A60&mode=design&t=lKFDRcgwjF9kDrO9-1) (design proposal is not yet available, as the final requirements have yet to be defined)
