### ISSUE TITLE
Collab

### ISSUE THREAD

**Issue by danielmoessner** [lawandorga/lawandorga-backend-service#368]
# Problem

`The best problem definition consists of a single specific story that shows why the status quo doesn’t work.`

Es müssen immer wieder die selben Briefköpfe und Fußzeilen an einen Text gepackt werden. Und dann gedruckt oder per pdf verschickt werden. Aktuell ist das umständlich über Word. Zum Beispiel Briefe oder ähnliches. Oft müssen auch genau dieselben Texte abgedruckt werden nur mit anderen Namen.

# Appetite

`How much time should be spent on this project?`

6 Wochen

# Solution

`How will the problem be solved? Add embedded and fat marker sketches.`

- Im Admin Bereich Funktionen für Vorlagen dieses Briefpapiers, also erstellen, bearbeiten und löschen von Briefköpfen und Fußzeilen.
- Mögliche Vorlagen: Briefkopf, Fußzeile

- Im Admin Bereich: Vorlagen für den Inhalt also die Texte erstellen, bearbeiten und löschen können.

- Beim Erstellen von einem Collab Dokument kann ich eine Vorlage oder Leer auswählen. Womit das Dokument befüllt wird.
- Beim Drucken von einem Collab Dokument kann ich Header und Fußzeile oder Leer auswählen. Die werden dann automatisch auf jeder Seite eingefügt.

## Optional Features

- besondere arten von vorlagen wie zb seitenleiste

# Rabbit holes

`What could go wrong? Or what problems might come up?`

- todo

# No-gos

`What will not be done?`

- kein newsletter editor
- keine bilder außer 1 logo
- kein teilen zwischen den rlc
- keine komplizierte formatierung wie zum beispiel andere schriftarten
- oder tabellen hintergrundfarben

**Comment by danielmoessner** [comment]
# Technical

Wir benötigen:

- Models (Vorlagen mit Type oder jeweils neues Model für jeden Type)
- Use Cases: CRUD auf Vorlagen, Create Collab updaten
- Frontend: Views für CRUD Vorlagen, Admin Bereich neuer Punkt
- Druck Funktion über das backend und nicht mit browser css

**Comment by hauf-toni** [comment]
**here is the [ui/ux proposal](https://www.figma.com/file/vwzbdSi917VEEbdpPC3LGv/Law-%26-Orga-x-Digitalfabrik?type=design&node-id=245%3A2896&mode=design&t=gdgoNZRPJmDlGxke-1),** based on the following design requirements:

⛳ **1. Template Management**
Admin Features:
💡 Creating Templates: Ability to design and save templates for letterheads and footers. Templates should support the inclusion of basic text and a single logo.
💡 Editing Templates: Facilitate the modification of existing templates to update text, logo placement, or basic formatting.
💡 Deleting Templates: Option to remove outdated or unnecessary templates from the system.
👉🏼 Content Template Integration: functionality for admins to create, edit, and delete text content templates that can be used in documents, such as standard legal disclosures, greetings, or closings.

⛳ **2. Document Creation and Editing**
Collab Document Setup:     
💡 Users should have the option to start a new document by choosing from existing templates (letterhead, footer) or begin with a blank document.

**Restrictions**
No Advanced Formatting or Multimedia: The system will not support complex formatting options like different fonts styles or table background colors.

**Comment by danielmoessner** [comment]
Erfolgreich abgeschlossen @LeandraH @JoeyStk @hauf-toni
